package com.kaiwaru.ticketing.service;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import org.springframework.stereotype.Service;

@Service
public class CityService {
    
    private final List<String> czechCities = Arrays.asList(
        "Praha",
        "Brno",
        "Ostrava",
        "Plzeň",
        "Liberec",
        "Olomouc",
        "Ústí nad Labem",
        "České Budějovice",
        "Hradec Králové",
        "Pardubice",
        "Zlín",
        "Havířov",
        "Kladno",
        "Most",
        "Opava",
        "Frýdek-Místek",
        "Karviná",
        "Jihlava",
        "Teplice",
        "Děčín",
        "Karlovy Vary",
        "Jablonec nad Nisou",
        "Mladá Boleslav",
        "Prostějov",
        "Přerov",
        "Chomutov",
        "Trutnov",
        "Třebíč",
        "Tábor",
        "Znojmo",
        "Příbram",
        "Cheb",
        "Orlová",
        "Břeclav",
        "Hodonín",
        "Česká Lípa",
        "Kopřivnice",
        "Nový Jičín",
        "Šumperk",
        "Kroměříž",
        "Valašské Meziříčí",
        "Uherské Hradiště",
        "Vsetín",
        "Blansko",
        "Třinec",
        "Beroun",
        "Týn nad Vltavou",
        "Kolín",
        "Kutná Hora",
        "Strakonice",
        "Písek",
        "Sokolov",
        "Litoměřice",
        "Louny",
        "Mělník",
        "Náchod",
        "Rychnov nad Kněžnou",
        "Svitavy",
        "Ústí nad Orlicí",
        "Jindřichův Hradec",
        "Pelhřimov",
        "Havlíčkův Brod",
        "Chrudim",
        "Bruntál",
        "Jeseník",
        "Krnov",
        "Vyškov",
        "Boskovice",
        "Rosice",
        "Kuřim",
        "Ivančice",
        "Hustopeče",
        "Mikulov",
        "Pohořelice",
        "Moravský Krumlov",
        "Kyjov",
        "Veselí nad Moravou",
        "Strážnice",
        "Slavkov u Brna",
        "Tišnov",
        "Šlapanice",
        "Modřice",
        "Rosice",
        "Adamov",
        "Letovice",
        "Velké Meziříčí",
        "Bystřice nad Pernštejnem",
        "Moravská Třebová",
        "Litomyšl",
        "Česká Třebová",
        "Lanškroun",
        "Ústí nad Orlicí",
        "Králíky",
        "Žamberk",
        "Hlinsko",
        "Polička",
        "Skuteč",
        "Pardubice",
        "Holice",
        "Lázně Bohdaneč",
        "Přelouč",
        "Heřmanův Městec",
        "Tábor",
        "Soběslav",
        "Veselí nad Lužnicí",
        "Dačice",
        "Třeboň",
        "Český Krumlov",
        "Prachatice",
        "Vimperk",
        "Kašperské Hory",
        "Sušice",
        "Klatovy",
        "Domažlice",
        "Tachov",
        "Stříbro",
        "Kralovice",
        "Nýřany",
        "Rokycany",
        "Beroun",
        "Hořovice",
        "Zdice",
        "Černošice",
        "Dobříš",
        "Rožmitál pod Třemšínem",
        "Sedlčany",
        "Benešov",
        "Vlašim",
        "Votice",
        "Týnec nad Sázavou",
        "Říčany",
        "Čerčany",
        "Brandýs nad Labem-Stará Boleslav",
        "Čelákovice",
        "Lysá nad Labem",
        "Poděbrady",
        "Nymburk",
        "Sadská",
        "Milovice",
        "Český Brod",
        "Uhlířské Janovice",
        "Kouřim",
        "Chlumec nad Cidlinou",
        "Nové Město nad Metují",
        "Dobruška",
        "Opočno",
        "Kostelec nad Orlicí",
        "Červený Kostelec",
        "Jaroměř",
        "Dvůr Králové nad Labem",
        "Hostinné",
        "Vrchlabí",
        "Jilemnice",
        "Železný Brod",
        "Turnov",
        "Mnichovo Hradiště",
        "Sobotka",
        "Nová Paka",
        "Jičín",
        "Hořice",
        "Nechanice",
        "Smiřice"
    );
    
    public List<String> searchCities(String query) {
        if (query == null || query.trim().isEmpty()) {
            return czechCities.stream().limit(10).collect(Collectors.toList());
        }
        
        String normalizedQuery = query.toLowerCase().trim();
        
        return czechCities.stream()
            .filter(city -> city.toLowerCase().contains(normalizedQuery))
            .limit(10)
            .collect(Collectors.toList());
    }
    
    public List<String> getAllCities() {
        return czechCities;
    }
}